### ISSUE TITLE
Missing migration (minor issue)

### ISSUE THREAD

**Issue by furins** [idlesign/django-sitegate#13]
Hi,
it seems that after latest changes in `models.py` (1 month ago) Django started complaining about a missing migration when running `python ./manage.py migrate` on a vanilla project (after installing django-sitegate using pip and after adding django-sitegate to  the installed apps): 

    out:   Your models have changes that are not yet reflected in a migration, and so won't be applied.
    out:   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

it's a minor issue, I can run `manage.py makemigrations` on every virtualenv as suggested and "patch" the installed PyPi package, but maybe you would add the migration in **django-sitegate** itself.

thanks
Stefano

**Comment by idlesign** [comment]
Hi,

Sure. You may verify it at master: https://github.com/idlesign/django-sitegate/commit/075691579ce3bf322a081329a43924248fe05483

Thank you for that report.
