### ISSUE TITLE
Django 1.8 says that there are changes that is not reflected in a migration when running migrate

### ISSUE THREAD

**Issue by binary-data** [idlesign/django-sitegate#19]
Hi!

When running `manage.py migrate` on Django 1.8 and django-sitegate 0.10.2, it tells me

```
Your models have changes that are not yet reflected in a migration, and so won't be applied.
Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

When running `makemigrations`, the output is:

```
Migrations for 'sitegate':
  0002_auto_20150929_1728.py:
    - Alter field code on emailconfirmation
    - Alter field code on invitationcode
```

But in general sitegate seems to work. Could you please add these migrations to a repository?

**Comment by idlesign** [comment]
Hi,

Sure. Seems to be fixed in master with https://github.com/idlesign/django-sitegate/commit/20076e59af1155580ef8503194e9b96bea737d6f

**Comment by binary-data** [comment]
Спасибо, ждём релиза :)

**Comment by idlesign** [comment]
You're welcome. Feel free to reopen if required.

Пожалуйста. Структурно ничего не поменялось, сообщение, в общем, ни о чём, поэтому, пока выпуск не случится, можно смело его игнорировать.
