### ISSUE TITLE
email address longer than 30 characters

### ISSUE THREAD

**Issue by onurmatik** [idlesign/django-sitegate#2]
With the email / password signup flow, the email address is inserted as the username. The max length for email address is 75 characters while the max for username is 30. What happens if an email address longer than 30 characters is used?

I tried this on my local machine with SQLite and it silently inserted the a > 30 character username but on other backends I think this will raise an exception.

**Comment by dedayoa** [comment]
Wow. It's been 3 years and this is what happens (with Postgresql).
It throws "DataError: value too long for type character varying(30)"

I tried to wrap my view in try...except, but didn't work as the error is thrown inside of the (in my case) the ModernSignup flow (the @signup_view decorator).
Is there a way to "wrap" this without modifying add_user inside '...sitegate\signup_flows\modern.py'?

I should mention that the username field is now varchar 150 in Django 1.10 as per https://code.djangoproject.com/ticket/20846

**Comment by idlesign** [comment]
Yeah, it's been a while %)
Some improvements are made, you can verify it from `master`.

**Comment by idlesign** [comment]
Fix released.
