### ISSUE TITLE
How to change "Default redirect URL"

### ISSUE THREAD

**Issue by dedayoa** [idlesign/django-sitegate#20]
Hi. Thanks for the work.
Kindly tell me how to change the Default redirect URL from /.
I have scoured the docs but can't find a setting key or API.

Thanks in Advance.

**Comment by dedayoa** [comment]
Ha! It only took looking inside django-sitegate/sitegate/signin_flows/base.py
I needed to pass redirect_to into the decorator
@signin_view(template='template.html', redirect_to='core:dashboard')

**Comment by idlesign** [comment]
Glad you've solved it.
I updated docs with redirect exmples.
